name: Build

on:

  push:

    branches: [ abseil ]

  pull_request:

    branches: [ abseil ]

jobs:

  build_wheels:

    name: Build wheels on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:

      matrix:

        os: [windows-2019]

    steps:

      - uses: actions/checkout@v2

      - name: Build wheels

        uses: pypa/cibuildwheel@v1.12.0
        with:
          package-dir: ./python

        env:

          CIBW_PLATFORM: windows

          CIBW_BUILD: cp39-win32

      - uses: actions/upload-artifact@v2

        with:

          path: ./wheelhouse/*.whl

