name: Build

on:

  push:

    branches: [ abseil ]

  pull_request:

    branches: [ abseil ]

jobs:

  build_wheels:

    name: Build wheels on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:

      matrix:

        os: [windows-2019]

    steps:
      - uses: actions/checkout@v2
      # - name: Clone Abseil
      #   run: git clone https://github.com/abseil/abseil-cpp.git
      #   shell: bash
      # - name: Link Abseil
      #   run: cd python && ln -s ../abseil-cpp/absl ./absl
      #   shell: bash
      - name: Install re2
        run: git clone https://github.com/AXVin/re2 re2-ins && cd re2-ins make && make install
        shell: bash
      - name: Build wheels
        uses: pypa/cibuildwheel@v1.12.0
        with:
          package-dir: ./python

        env:

          CIBW_PLATFORM: windows

          CIBW_BUILD: cp39-win32
          CIBW_BEFORE_BUILD: pip install pybind11

      - uses: actions/upload-artifact@v2

        with:

          path: ./wheelhouse/*.whl

